[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationIpopt = "43fad042-7963-4b32-ab19-e2a4f9a67124"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TidierData = "fe2206b3-d496-4ee9-a338-6a095c4ece80"
